// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GrpcCsharp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Grpcsharp {

  /// <summary>Holder for reflection information generated from GrpcCsharp.proto</summary>
  public static partial class GrpcCsharpReflection {

    #region Descriptor
    /// <summary>File descriptor for GrpcCsharp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GrpcCsharpReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBHcnBjQ3NoYXJwLnByb3RvEglncnBjc2hhcnAiOAoLQ2xpZW50SGVsbG8S",
            "EgoKY2xpZW50TmFtZRgBIAEoCRIVCg1jbGllbnRNZXNzYWdlGAIgASgJIk4K",
            "C1NlcnZlckhlbGxvEhIKCnNlcnZlck5hbWUYASABKAkSFAoMc2VydmVyTnVt",
            "YmVyGAIgASgDEhUKDXNlcnZlck1lc3NhZ2UYAyABKAkyRgoEQ2hhdBI+CgpH",
            "ZXRNZXNzYWdlEhYuZ3JwY3NoYXJwLkNsaWVudEhlbGxvGhYuZ3JwY3NoYXJw",
            "LlNlcnZlckhlbGxvIgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpcsharp.ClientHello), global::Grpcsharp.ClientHello.Parser, new[]{ "ClientName", "ClientMessage" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpcsharp.ServerHello), global::Grpcsharp.ServerHello.Parser, new[]{ "ServerName", "ServerNumber", "ServerMessage" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ClientHello : pb::IMessage<ClientHello> {
    private static readonly pb::MessageParser<ClientHello> _parser = new pb::MessageParser<ClientHello>(() => new ClientHello());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientHello> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpcsharp.GrpcCsharpReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientHello() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientHello(ClientHello other) : this() {
      clientName_ = other.clientName_;
      clientMessage_ = other.clientMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientHello Clone() {
      return new ClientHello(this);
    }

    /// <summary>Field number for the "clientName" field.</summary>
    public const int ClientNameFieldNumber = 1;
    private string clientName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ClientName {
      get { return clientName_; }
      set {
        clientName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "clientMessage" field.</summary>
    public const int ClientMessageFieldNumber = 2;
    private string clientMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ClientMessage {
      get { return clientMessage_; }
      set {
        clientMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientHello);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientHello other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientName != other.ClientName) return false;
      if (ClientMessage != other.ClientMessage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientName.Length != 0) hash ^= ClientName.GetHashCode();
      if (ClientMessage.Length != 0) hash ^= ClientMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ClientName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientName);
      }
      if (ClientMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ClientMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ClientName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientName);
      }
      if (ClientMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientHello other) {
      if (other == null) {
        return;
      }
      if (other.ClientName.Length != 0) {
        ClientName = other.ClientName;
      }
      if (other.ClientMessage.Length != 0) {
        ClientMessage = other.ClientMessage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ClientName = input.ReadString();
            break;
          }
          case 18: {
            ClientMessage = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ServerHello : pb::IMessage<ServerHello> {
    private static readonly pb::MessageParser<ServerHello> _parser = new pb::MessageParser<ServerHello>(() => new ServerHello());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ServerHello> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpcsharp.GrpcCsharpReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerHello() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerHello(ServerHello other) : this() {
      serverName_ = other.serverName_;
      serverNumber_ = other.serverNumber_;
      serverMessage_ = other.serverMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerHello Clone() {
      return new ServerHello(this);
    }

    /// <summary>Field number for the "serverName" field.</summary>
    public const int ServerNameFieldNumber = 1;
    private string serverName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ServerName {
      get { return serverName_; }
      set {
        serverName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "serverNumber" field.</summary>
    public const int ServerNumberFieldNumber = 2;
    private long serverNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ServerNumber {
      get { return serverNumber_; }
      set {
        serverNumber_ = value;
      }
    }

    /// <summary>Field number for the "serverMessage" field.</summary>
    public const int ServerMessageFieldNumber = 3;
    private string serverMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ServerMessage {
      get { return serverMessage_; }
      set {
        serverMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ServerHello);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ServerHello other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServerName != other.ServerName) return false;
      if (ServerNumber != other.ServerNumber) return false;
      if (ServerMessage != other.ServerMessage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ServerName.Length != 0) hash ^= ServerName.GetHashCode();
      if (ServerNumber != 0L) hash ^= ServerNumber.GetHashCode();
      if (ServerMessage.Length != 0) hash ^= ServerMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ServerName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ServerName);
      }
      if (ServerNumber != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ServerNumber);
      }
      if (ServerMessage.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ServerMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ServerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerName);
      }
      if (ServerNumber != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ServerNumber);
      }
      if (ServerMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ServerHello other) {
      if (other == null) {
        return;
      }
      if (other.ServerName.Length != 0) {
        ServerName = other.ServerName;
      }
      if (other.ServerNumber != 0L) {
        ServerNumber = other.ServerNumber;
      }
      if (other.ServerMessage.Length != 0) {
        ServerMessage = other.ServerMessage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ServerName = input.ReadString();
            break;
          }
          case 16: {
            ServerNumber = input.ReadInt64();
            break;
          }
          case 26: {
            ServerMessage = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
