spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://git(replace)
          username: (replace)
          password: (replace)
          basedir: G:\Projects\(replace)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: configClient
server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: "*"