spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/configurationcloud/configuration.git
          username: (replace)
          password: (replace)
          basedir: G:\Projects\(replace)
  rabbitmq:
    host: 192.168.1.233
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9898
management:
  endpoints:
    web:
      exposure:
        include: "*"