// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GrpcCsharp.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Grpcsharp {
  public static partial class Chat
  {
    static readonly string __ServiceName = "grpcsharp.Chat";

    static readonly grpc::Marshaller<global::Grpcsharp.ClientHello> __Marshaller_ClientHello = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpcsharp.ClientHello.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Grpcsharp.ServerHello> __Marshaller_ServerHello = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpcsharp.ServerHello.Parser.ParseFrom);

    static readonly grpc::Method<global::Grpcsharp.ClientHello, global::Grpcsharp.ServerHello> __Method_GetMessage = new grpc::Method<global::Grpcsharp.ClientHello, global::Grpcsharp.ServerHello>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMessage",
        __Marshaller_ClientHello,
        __Marshaller_ServerHello);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Grpcsharp.GrpcCsharpReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Chat</summary>
    public abstract partial class ChatBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Grpcsharp.ServerHello> GetMessage(global::Grpcsharp.ClientHello request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Chat</summary>
    public partial class ChatClient : grpc::ClientBase<ChatClient>
    {
      /// <summary>Creates a new client for Chat</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ChatClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Chat that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ChatClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ChatClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ChatClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Grpcsharp.ServerHello GetMessage(global::Grpcsharp.ClientHello request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Grpcsharp.ServerHello GetMessage(global::Grpcsharp.ClientHello request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetMessage, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Grpcsharp.ServerHello> GetMessageAsync(global::Grpcsharp.ClientHello request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Grpcsharp.ServerHello> GetMessageAsync(global::Grpcsharp.ClientHello request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetMessage, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ChatClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ChatClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ChatBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetMessage, serviceImpl.GetMessage).Build();
    }

  }
}
#endregion
